Fix error with missing argument
Fixes this issue: test/helpers/util.ts:33:9 - error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?